#ifndef GAUDICORESVC_VERSION
/* Automatically generated file: do not modify! */
#ifndef CALC_GAUDI_VERSION
#define CALC_GAUDI_VERSION(maj,min) (((maj) << 16) + (min))
#endif
#define GAUDICORESVC_MAJOR_VERSION 1
#define GAUDICORESVC_MINOR_VERSION 3
#define GAUDICORESVC_PATCH_VERSION 0
#define GAUDICORESVC_VERSION CALC_GAUDI_VERSION(GAUDICORESVC_MAJOR_VERSION,GAUDICORESVC_MINOR_VERSION)
#endif
